version: "3"
services:
  api:
    build: .
    container_name: "fastapi-application"
    image:
      "archanathyagaraj/moon_5:1.0"
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    restart: "always"
